sudo: required
language: java
jdk:
    - oraclejdk8
    - oraclejdk9
script:
  - export GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs='-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m'"
  - travis_wait ./gradlew install check --stacktrace --info --no-daemon
dist: trusty
